const axios = require('axios');

// GET /github/repos
const getUserRepos = async (req, res) => {
  try {
    const response = await axios.get('https://api.github.com/user/repos', {
      headers: {
        Authorization: `Bearer ${req.user.accessToken}`,
        Accept: 'application/vnd.github.mercy-preview+json',
      },
      params: { sort: 'updated', per_page: 20 },
    });
    res.json(response.data);
  } catch (err) {
    console.error('Error fetching repos:', err.message);
    res.status(500).json({ message: 'Failed to fetch repositories' });
  }
};

// GET /github/repos/:owner/:repo/pulls
const getRepoPulls = async (req, res) => {
  const { owner, repo } = req.params;
  try {
    const response = await axios.get(
      `https://api.github.com/repos/${owner}/${repo}/pulls`,
      {
        headers: {
          Authorization: `Bearer ${req.user.accessToken}`,
          Accept: 'application/vnd.github.v3+json',
        },
        params: { state: 'open', per_page: 30 },
      }
    );
    res.json(response.data);
  } catch (err) {
    console.error('Error fetching PRs:', err.message);
    res.status(500).json({ message: 'Failed to fetch pull requests' });
  }
};

// GET /github/repos/:owner/:repo/pulls/:pull_number/files
const getPullFiles = async (req, res) => {
  const { owner, repo, pull_number } = req.params;
  try {
    const response = await axios.get(
      `https://api.github.com/repos/${owner}/${repo}/pulls/${pull_number}/files`,
      {
        headers: {
          Authorization: `Bearer ${req.user.accessToken}`,
          Accept: 'application/vnd.github.v3+json',
        },
      }
    );
    res.json(response.data);
  } catch (err) {
    console.error('Error fetching PR files:', err.message);
    res.status(500).json({ message: 'Failed to fetch pull request files' });
  }
};

// GET /github/pulls/:owner/:repo/:pull_number/diff
const getPullDiff = async (req, res) => {
  const { owner, repo, pull_number } = req.params;
  try {
    const response = await axios.get(
      `https://api.github.com/repos/${owner}/${repo}/pulls/${pull_number}`,
      {
        headers: {
          Authorization: `Bearer ${req.user.accessToken}`,
          Accept: 'application/vnd.github.v3.diff',
        },
      }
    );
    res.set('Content-Type', 'text/plain');
    res.send(response.data);
  } catch (err) {
    console.error('Error fetching diff:', err.message);
    res.status(500).json({ message: 'Failed to fetch diff' });
  }
};

// POST /github/comment — post formatted review as GitHub PR comment
const postReviewComment = async (req, res) => {
  const { owner, repo, pull_number, summary, issues, suggestions, score, scoreBreakdown, verdict } = req.body;

  const verdictEmoji = verdict === 'APPROVE' ? '✅' : verdict === 'REQUEST CHANGES' ? '❌' : '💬';

  const body = `## 🤖 PRism AI Review

### 📋 Summary
${summary}

---

### 🐛 Issues Found
${issues}

---

### 💡 Suggestions
${suggestions}

---

### 📊 Score Breakdown
| Category | Score |
|---|---|
| Code Quality | ${scoreBreakdown?.codeQuality ?? 'N/A'}/25 |
| Security | ${scoreBreakdown?.security ?? 'N/A'}/25 |
| Performance | ${scoreBreakdown?.performance ?? 'N/A'}/25 |
| Readability | ${scoreBreakdown?.readability ?? 'N/A'}/25 |
| **Total** | **${score ?? 'N/A'}/100** |

### Verdict: ${verdictEmoji} ${verdict}

---
*Generated by [PRism](https://github.com/PRism) • Powered by LLaMA 3.3 70B via Groq*`;

  try {
    await axios.post(
      `https://api.github.com/repos/${owner}/${repo}/issues/${pull_number}/comments`,
      { body },
      {
        headers: {
          Authorization: `Bearer ${req.user.accessToken}`,
          Accept: 'application/vnd.github.v3+json',
        },
      }
    );
    res.json({ message: 'Comment posted successfully' });
  } catch (err) {
    console.error('Error posting comment:', err.message);
    res.status(500).json({ message: 'Failed to post comment to GitHub' });
  }
};

module.exports = { getUserRepos, getRepoPulls, getPullFiles, getPullDiff, postReviewComment };
